/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import java.awt.Frame;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;


/**
 *
 * @author igohs
 */
public final class SalesGUI extends javax.swing.JPanel {

    
        MainForm main = new MainForm();
        boolean checkout_ = false;
        boolean deletbill_ = false;
        boolean newbill_ = false;
        boolean search_ = false;
        boolean deletitem_ = false;
        Color maincol = new Color(0,168,255);
        Color CheckoutMain = new Color(243,156,18);
        Color CheckoutSel = new Color(230,126,34);
        Color DeleteMain = new Color(231,76,60);
        Color DeleteSel = new Color(192,57,43);
        Color secol = new Color(0,168,255);
        Color slectedcol = new Color(52,61,80);
        
    public SalesGUI() {
        //Inv1.setVisible(false);
        initComponents();
        initializeTables();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        deletbill_p = new javax.swing.JPanel();
        deletbill_b = new javax.swing.JButton();
        newbill_p = new javax.swing.JPanel();
        newbill_b = new javax.swing.JButton();
        checkout_p = new javax.swing.JPanel();
        checkout_b = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        sales_table = new javax.swing.JTable();
        test_table = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(47, 54, 64));

        jPanel1.setBackground(new java.awt.Color(47, 54, 64));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Subtotal:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("3 SAR");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Tax :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("15%");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Total:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("3.45 SAR");

        deletbill_p.setBackground(new java.awt.Color(231, 76, 60));
        deletbill_p.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(28, 54, 82), 2, true));

        deletbill_b.setBackground(new java.awt.Color(39, 73, 109));
        deletbill_b.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        deletbill_b.setForeground(new java.awt.Color(240, 240, 240));
        deletbill_b.setText("Delete Bill");
        deletbill_b.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 40, 80)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 40, 80))));
        deletbill_b.setBorderPainted(false);
        deletbill_b.setContentAreaFilled(false);
        deletbill_b.setDefaultCapable(false);
        deletbill_b.setFocusPainted(false);
        deletbill_b.setFocusable(false);
        deletbill_b.setHideActionText(true);
        deletbill_b.setRequestFocusEnabled(false);
        deletbill_b.setVerifyInputWhenFocusTarget(false);
        deletbill_b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deletbill_bMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deletbill_bMouseExited(evt);
            }
        });
        deletbill_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletbill_bActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deletbill_pLayout = new javax.swing.GroupLayout(deletbill_p);
        deletbill_p.setLayout(deletbill_pLayout);
        deletbill_pLayout.setHorizontalGroup(
            deletbill_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deletbill_pLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deletbill_b, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                .addContainerGap())
        );
        deletbill_pLayout.setVerticalGroup(
            deletbill_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deletbill_b)
        );

        newbill_p.setBackground(new java.awt.Color(0, 168, 255));
        newbill_p.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(28, 54, 82), 2, true));

        newbill_b.setBackground(new java.awt.Color(39, 73, 109));
        newbill_b.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        newbill_b.setForeground(new java.awt.Color(240, 240, 240));
        newbill_b.setText("New Bill");
        newbill_b.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 40, 80)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 40, 80))));
        newbill_b.setBorderPainted(false);
        newbill_b.setContentAreaFilled(false);
        newbill_b.setDefaultCapable(false);
        newbill_b.setFocusPainted(false);
        newbill_b.setFocusable(false);
        newbill_b.setHideActionText(true);
        newbill_b.setRequestFocusEnabled(false);
        newbill_b.setVerifyInputWhenFocusTarget(false);
        newbill_b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newbill_bMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newbill_bMouseExited(evt);
            }
        });
        newbill_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newbill_bActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newbill_pLayout = new javax.swing.GroupLayout(newbill_p);
        newbill_p.setLayout(newbill_pLayout);
        newbill_pLayout.setHorizontalGroup(
            newbill_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newbill_pLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newbill_b, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addContainerGap())
        );
        newbill_pLayout.setVerticalGroup(
            newbill_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newbill_b, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        checkout_p.setBackground(new java.awt.Color(243, 156, 18));
        checkout_p.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(28, 54, 82), 2, true));

        checkout_b.setBackground(new java.awt.Color(0, 168, 255));
        checkout_b.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        checkout_b.setForeground(new java.awt.Color(240, 240, 240));
        checkout_b.setText("checkout");
        checkout_b.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 40, 80)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 40, 80))));
        checkout_b.setBorderPainted(false);
        checkout_b.setContentAreaFilled(false);
        checkout_b.setDefaultCapable(false);
        checkout_b.setFocusPainted(false);
        checkout_b.setFocusable(false);
        checkout_b.setHideActionText(true);
        checkout_b.setRequestFocusEnabled(false);
        checkout_b.setVerifyInputWhenFocusTarget(false);
        checkout_b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                checkout_bMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                checkout_bMouseExited(evt);
            }
        });
        checkout_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkout_bActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout checkout_pLayout = new javax.swing.GroupLayout(checkout_p);
        checkout_p.setLayout(checkout_pLayout);
        checkout_pLayout.setHorizontalGroup(
            checkout_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkout_pLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkout_b, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addContainerGap())
        );
        checkout_pLayout.setVerticalGroup(
            checkout_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkout_pLayout.createSequentialGroup()
                .addComponent(checkout_b, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        sales_table.setBackground(new java.awt.Color(47, 54, 64));
        sales_table.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        sales_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "item", "Qty", "price"
            }
        ));
        sales_table.setGridColor(new java.awt.Color(63, 77, 97));
        jScrollPane1.setViewportView(sales_table);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        test_table.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(test_table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(checkout_p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel7))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel5))))
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(newbill_p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deletbill_p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(newbill_p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletbill_p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(test_table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkout_p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(47, 54, 64));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 121, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void checkout_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkout_bActionPerformed
        checkout_ = true;
        deletbill_ = false;
        newbill_ = false;
        search_ = false;
        deletitem_ = false;
        
        deletbill_p.setBackground(DeleteMain);
        checkout_p.setBackground(CheckoutMain);

        newbill_p.setBackground(secol);
        
        PaymentWindow pay = new PaymentWindow();
        pay.setVisible(true);
    }//GEN-LAST:event_checkout_bActionPerformed

    private void checkout_bMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkout_bMouseExited
        if (checkout_ != true)
        {
            checkout_p.setBackground(CheckoutMain);
        }
        else
        checkout_p.setBackground(CheckoutSel);
    }//GEN-LAST:event_checkout_bMouseExited

    private void checkout_bMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkout_bMouseEntered
        checkout_p.setBackground(CheckoutSel);
    }//GEN-LAST:event_checkout_bMouseEntered

    private void newbill_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newbill_bActionPerformed
        checkout_ = false;
        deletbill_ = false;
        newbill_ = true;
        search_ = false;
        deletitem_ = false;

        deletbill_p.setBackground(DeleteMain);
        checkout_p.setBackground(CheckoutMain);

        newbill_p.setBackground(secol);


        main.updateMainPanel(new SalesGUI());
        main.setVisible(true);

    }//GEN-LAST:event_newbill_bActionPerformed

    private void newbill_bMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newbill_bMouseExited
        if (newbill_ != true)
        {
            newbill_p.setBackground(secol);
        }
        else
        newbill_p.setBackground(secol);
    }//GEN-LAST:event_newbill_bMouseExited

    private void newbill_bMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newbill_bMouseEntered
        newbill_p.setBackground(slectedcol);
    }//GEN-LAST:event_newbill_bMouseEntered

    private void deletbill_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletbill_bActionPerformed
        checkout_ = false;
        deletbill_ = true;
        newbill_ = false;
        search_ = false;
        deletitem_ = false;

        deletbill_p.setBackground(DeleteMain);
        checkout_p.setBackground(CheckoutMain);

        newbill_p.setBackground(secol);


        // Get all open frames
        Frame[] frames = Frame.getFrames();

        // Count visible frames
        int visibleFrameCount = 0;
        for (Frame frame : frames) {
            if (frame instanceof JFrame && frame.isVisible()) {
                visibleFrameCount++;
            }
        }

        // Check if there is more than one visible frame
        if (visibleFrameCount > 1) {
            // Close the current frame
            JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
            currentFrame.dispose();
        }
        else if(visibleFrameCount <= 1){
            main.updateMainPanel(new SalesGUI());

        }
    }//GEN-LAST:event_deletbill_bActionPerformed

    private void deletbill_bMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletbill_bMouseExited
        if (deletbill_ != true)
        {
            deletbill_p.setBackground(DeleteMain);
        }
        else
        deletbill_p.setBackground(DeleteSel);
    }//GEN-LAST:event_deletbill_bMouseExited

    private void deletbill_bMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletbill_bMouseEntered

        deletbill_p.setBackground(DeleteSel);
    }//GEN-LAST:event_deletbill_bMouseEntered

    
    private void initializeTables() {
        // Initialize table1 with some sample data
        DefaultTableModel model1 = new DefaultTableModel(
            new Object[][]{
                {"John", 8, 30},
                {"Jane", 5, 25},
                {"John", 8, 30},
                {"Jane", 5, 25},
                {"John", 8, 30},
                {"Jane", 5, 25},
                {"John", 8, 30},
                {"Jane", 5, 25},
                {"John", 8, 30},
                {"Jane", 5, 25},
                {"John", 8, 30},
                {"Jane", 5, 25},
                {"John", 8, 30},
                {"Jane", 5, 25},
                {"John", 8, 30},
                {"Jane", 5, 25},
                {"John", 8, 30},
                {"Jane", 5, 25},
                {"John", 8, 30},
                {"Jane", 5, 25},
                {"John", 8, 30},
                {"Jane", 5, 25},
                {"John", 8, 30},
                {"Jane", 5, 25},
                {"John", 8, 30},
                {"Jane", 5, 25},
                {"lol",6,8}
            },
            new String[]{"item", "Qty", "price"}
        );
        sales_table.setModel(model1);
    }
    
     public JTable getinv_table() {
        return sales_table;
    }   
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkout_b;
    private javax.swing.JPanel checkout_p;
    private javax.swing.JButton deletbill_b;
    private javax.swing.JPanel deletbill_p;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton newbill_b;
    private javax.swing.JPanel newbill_p;
    public javax.swing.JTable sales_table;
    private javax.swing.JScrollPane test_table;
    // End of variables declaration//GEN-END:variables
}
