/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import java.awt.Frame;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author igohs
 */
public class SalesGUI extends javax.swing.JPanel {

    
        MainForm main = new MainForm();
        boolean checkout_ = false;
        boolean deletbill_ = false;
        boolean newbill_ = false;
        boolean search_ = false;
        boolean deletitem_ = false;
        Color maincol = new Color(0,168,255);
        Color CheckoutMain = new Color(243,156,18);
        Color CheckoutSel = new Color(230,126,34);
        Color DeleteMain = new Color(231,76,60);
        Color DeleteSel = new Color(192,57,43);
        Color secol = new Color(0,168,255);
        Color slectedcol = new Color(52,61,80);
    public SalesGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        deletbill_p = new javax.swing.JPanel();
        deletbill_b = new javax.swing.JButton();
        newbill_p = new javax.swing.JPanel();
        newbill_b = new javax.swing.JButton();
        checkout_p = new javax.swing.JPanel();
        checkout_b = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        deletitem_p = new javax.swing.JPanel();
        deletitem_b = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        search_p = new javax.swing.JPanel();
        search_b = new javax.swing.JButton();

        setBackground(new java.awt.Color(47, 54, 64));

        jScrollPane1.setBackground(new java.awt.Color(47, 54, 64));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBackground(new java.awt.Color(47, 54, 64));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jTable1.setForeground(new java.awt.Color(240, 240, 240));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1), "Milk",  new Integer(1),  new Float(7.0)},
                { new Integer(2), "Bread",  new Integer(3),  new Float(4.0)},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "N", "Product Name", "Quantity", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setRowHeight(66);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(100);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        jPanel1.setBackground(new java.awt.Color(47, 54, 64));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Subtotal:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("3 SAR");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Tax :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("15%");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Total:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("3.45 SAR");

        deletbill_p.setBackground(new java.awt.Color(231, 76, 60));
        deletbill_p.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(28, 54, 82), 2, true));

        deletbill_b.setBackground(new java.awt.Color(39, 73, 109));
        deletbill_b.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        deletbill_b.setForeground(new java.awt.Color(240, 240, 240));
        deletbill_b.setText("Delete Bill");
        deletbill_b.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 40, 80)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 40, 80))));
        deletbill_b.setBorderPainted(false);
        deletbill_b.setContentAreaFilled(false);
        deletbill_b.setDefaultCapable(false);
        deletbill_b.setFocusPainted(false);
        deletbill_b.setFocusable(false);
        deletbill_b.setHideActionText(true);
        deletbill_b.setRequestFocusEnabled(false);
        deletbill_b.setVerifyInputWhenFocusTarget(false);
        deletbill_b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deletbill_bMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deletbill_bMouseExited(evt);
            }
        });
        deletbill_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletbill_bActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deletbill_pLayout = new javax.swing.GroupLayout(deletbill_p);
        deletbill_p.setLayout(deletbill_pLayout);
        deletbill_pLayout.setHorizontalGroup(
            deletbill_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deletbill_pLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deletbill_b, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addContainerGap())
        );
        deletbill_pLayout.setVerticalGroup(
            deletbill_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deletbill_b, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
        );

        newbill_p.setBackground(new java.awt.Color(0, 168, 255));
        newbill_p.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(28, 54, 82), 2, true));

        newbill_b.setBackground(new java.awt.Color(39, 73, 109));
        newbill_b.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        newbill_b.setForeground(new java.awt.Color(240, 240, 240));
        newbill_b.setText("New Bill");
        newbill_b.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 40, 80)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 40, 80))));
        newbill_b.setBorderPainted(false);
        newbill_b.setContentAreaFilled(false);
        newbill_b.setDefaultCapable(false);
        newbill_b.setFocusPainted(false);
        newbill_b.setFocusable(false);
        newbill_b.setHideActionText(true);
        newbill_b.setRequestFocusEnabled(false);
        newbill_b.setVerifyInputWhenFocusTarget(false);
        newbill_b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newbill_bMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newbill_bMouseExited(evt);
            }
        });
        newbill_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newbill_bActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newbill_pLayout = new javax.swing.GroupLayout(newbill_p);
        newbill_p.setLayout(newbill_pLayout);
        newbill_pLayout.setHorizontalGroup(
            newbill_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newbill_pLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newbill_b, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addContainerGap())
        );
        newbill_pLayout.setVerticalGroup(
            newbill_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newbill_b, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
        );

        checkout_p.setBackground(new java.awt.Color(243, 156, 18));
        checkout_p.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(28, 54, 82), 2, true));

        checkout_b.setBackground(new java.awt.Color(0, 168, 255));
        checkout_b.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        checkout_b.setForeground(new java.awt.Color(240, 240, 240));
        checkout_b.setText("checkout");
        checkout_b.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 40, 80)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 40, 80))));
        checkout_b.setBorderPainted(false);
        checkout_b.setContentAreaFilled(false);
        checkout_b.setDefaultCapable(false);
        checkout_b.setFocusPainted(false);
        checkout_b.setFocusable(false);
        checkout_b.setHideActionText(true);
        checkout_b.setRequestFocusEnabled(false);
        checkout_b.setVerifyInputWhenFocusTarget(false);
        checkout_b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                checkout_bMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                checkout_bMouseExited(evt);
            }
        });
        checkout_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkout_bActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout checkout_pLayout = new javax.swing.GroupLayout(checkout_p);
        checkout_p.setLayout(checkout_pLayout);
        checkout_pLayout.setHorizontalGroup(
            checkout_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkout_pLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkout_b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        checkout_pLayout.setVerticalGroup(
            checkout_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkout_pLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(checkout_b, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        deletitem_p.setBackground(new java.awt.Color(231, 76, 60));
        deletitem_p.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(28, 54, 82), 2, true));

        deletitem_b.setBackground(new java.awt.Color(39, 73, 109));
        deletitem_b.setFont(new java.awt.Font("SansSerif", 0, 32)); // NOI18N
        deletitem_b.setForeground(new java.awt.Color(240, 240, 240));
        deletitem_b.setText("Delete Item");
        deletitem_b.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 40, 80)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 40, 80))));
        deletitem_b.setBorderPainted(false);
        deletitem_b.setContentAreaFilled(false);
        deletitem_b.setDefaultCapable(false);
        deletitem_b.setFocusPainted(false);
        deletitem_b.setFocusable(false);
        deletitem_b.setHideActionText(true);
        deletitem_b.setRequestFocusEnabled(false);
        deletitem_b.setVerifyInputWhenFocusTarget(false);
        deletitem_b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deletitem_bMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deletitem_bMouseExited(evt);
            }
        });
        deletitem_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletitem_bActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deletitem_pLayout = new javax.swing.GroupLayout(deletitem_p);
        deletitem_p.setLayout(deletitem_pLayout);
        deletitem_pLayout.setHorizontalGroup(
            deletitem_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deletitem_pLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deletitem_b, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addContainerGap())
        );
        deletitem_pLayout.setVerticalGroup(
            deletitem_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deletitem_b, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkout_p, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator3)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(deletbill_p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deletitem_p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(59, 59, 59)
                    .addComponent(newbill_p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(55, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(deletbill_p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(checkout_p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(deletitem_p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(newbill_p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(541, Short.MAX_VALUE)))
        );

        jPanel2.setBackground(new java.awt.Color(47, 54, 64));

        jTextField1.setBackground(new java.awt.Color(59, 94, 132));
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(240, 240, 240));
        jTextField1.setText("Search product");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        search_p.setBackground(new java.awt.Color(0, 168, 255));
        search_p.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(28, 54, 82), 2, true));

        search_b.setBackground(new java.awt.Color(0, 168, 255));
        search_b.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        search_b.setForeground(new java.awt.Color(240, 240, 240));
        search_b.setText("search");
        search_b.setActionCommand("delet item");
        search_b.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 40, 80)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 40, 80))));
        search_b.setBorderPainted(false);
        search_b.setContentAreaFilled(false);
        search_b.setDefaultCapable(false);
        search_b.setFocusPainted(false);
        search_b.setFocusable(false);
        search_b.setHideActionText(true);
        search_b.setRequestFocusEnabled(false);
        search_b.setVerifyInputWhenFocusTarget(false);
        search_b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                search_bMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                search_bMouseExited(evt);
            }
        });
        search_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_bActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout search_pLayout = new javax.swing.GroupLayout(search_p);
        search_p.setLayout(search_pLayout);
        search_pLayout.setHorizontalGroup(
            search_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(search_b, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
        );
        search_pLayout.setVerticalGroup(
            search_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(search_b, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(search_p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(search_p, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void search_bMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_bMouseEntered
        search_p.setBackground(slectedcol);
    }//GEN-LAST:event_search_bMouseEntered

    private void search_bMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_bMouseExited
        if (search_ != true)
        {
            search_p.setBackground(secol);
        }
        else
        search_p.setBackground(secol);
    }//GEN-LAST:event_search_bMouseExited

    private void search_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_bActionPerformed
        checkout_ = false;
        deletbill_ = false;
        newbill_ = false;
        search_ = true;
        deletitem_ = false;
        
        deletbill_p.setBackground(DeleteMain);
        checkout_p.setBackground(CheckoutMain);
        deletitem_p.setBackground(DeleteMain);
        newbill_p.setBackground(secol);
        search_p.setBackground(secol);
    }//GEN-LAST:event_search_bActionPerformed

    private void deletitem_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletitem_bActionPerformed
        checkout_ = false;
        deletbill_ = false;
        newbill_ = false;
        search_ = false;
        deletitem_ = true;

        deletbill_p.setBackground(DeleteMain);
        checkout_p.setBackground(CheckoutMain);
        deletitem_p.setBackground(DeleteMain);
        newbill_p.setBackground(secol);
        search_p.setBackground(secol);

    }//GEN-LAST:event_deletitem_bActionPerformed

    private void deletitem_bMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletitem_bMouseExited
        if (deletitem_ != true)
        {
            deletitem_p.setBackground(DeleteMain);
        }
        else
        deletitem_p.setBackground(DeleteSel);
    }//GEN-LAST:event_deletitem_bMouseExited

    private void deletitem_bMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletitem_bMouseEntered
        deletitem_p.setBackground(DeleteSel);
    }//GEN-LAST:event_deletitem_bMouseEntered

    private void checkout_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkout_bActionPerformed
        checkout_ = true;
        deletbill_ = false;
        newbill_ = false;
        search_ = false;
        deletitem_ = false;

        deletbill_p.setBackground(DeleteMain);
        checkout_p.setBackground(CheckoutMain);
        deletitem_p.setBackground(DeleteMain);
        newbill_p.setBackground(secol);
        search_p.setBackground(secol);

        PaymentWindow pay = new PaymentWindow();
        pay.setVisible(true);
    }//GEN-LAST:event_checkout_bActionPerformed

    private void checkout_bMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkout_bMouseExited
        if (checkout_ != true)
        {
            checkout_p.setBackground(CheckoutMain);
        }
        else
        checkout_p.setBackground(CheckoutSel);
    }//GEN-LAST:event_checkout_bMouseExited

    private void checkout_bMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkout_bMouseEntered
        checkout_p.setBackground(CheckoutSel);
    }//GEN-LAST:event_checkout_bMouseEntered

    private void newbill_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newbill_bActionPerformed
        checkout_ = false;
        deletbill_ = false;
        newbill_ = true;
        search_ = false;
        deletitem_ = false;

        deletbill_p.setBackground(DeleteMain);
        checkout_p.setBackground(CheckoutMain);
        deletitem_p.setBackground(DeleteMain);
        newbill_p.setBackground(secol);
        search_p.setBackground(secol);

        main.updateMainPanel(new SalesGUI());
        main.setVisible(true);

    }//GEN-LAST:event_newbill_bActionPerformed

    private void newbill_bMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newbill_bMouseExited
        if (newbill_ != true)
        {
            newbill_p.setBackground(secol);
        }
        else
        newbill_p.setBackground(secol);
    }//GEN-LAST:event_newbill_bMouseExited

    private void newbill_bMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newbill_bMouseEntered
        newbill_p.setBackground(slectedcol);
    }//GEN-LAST:event_newbill_bMouseEntered

    private void deletbill_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletbill_bActionPerformed
        checkout_ = false;
        deletbill_ = true;
        newbill_ = false;
        search_ = false;
        deletitem_ = false;

        deletbill_p.setBackground(DeleteMain);
        checkout_p.setBackground(CheckoutMain);
        deletitem_p.setBackground(DeleteMain);
        newbill_p.setBackground(secol);
        search_p.setBackground(secol);

        // Get all open frames
        Frame[] frames = Frame.getFrames();

        // Count visible frames
        int visibleFrameCount = 0;
        for (Frame frame : frames) {
            if (frame instanceof JFrame && frame.isVisible()) {
                visibleFrameCount++;
            }
        }

        // Check if there is more than one visible frame
        if (visibleFrameCount > 1) {
            // Close the current frame
            JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
            currentFrame.dispose();
        }
        else if(visibleFrameCount <= 1){
            main.updateMainPanel(new SalesGUI());

        }
    }//GEN-LAST:event_deletbill_bActionPerformed

    private void deletbill_bMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletbill_bMouseExited
        if (deletbill_ != true)
        {
            deletbill_p.setBackground(DeleteMain);
        }
        else
        deletbill_p.setBackground(DeleteSel);
    }//GEN-LAST:event_deletbill_bMouseExited

    private void deletbill_bMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletbill_bMouseEntered

        deletbill_p.setBackground(DeleteSel);
    }//GEN-LAST:event_deletbill_bMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkout_b;
    private javax.swing.JPanel checkout_p;
    private javax.swing.JButton deletbill_b;
    private javax.swing.JPanel deletbill_p;
    private javax.swing.JButton deletitem_b;
    private javax.swing.JPanel deletitem_p;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton newbill_b;
    private javax.swing.JPanel newbill_p;
    private javax.swing.JButton search_b;
    private javax.swing.JPanel search_p;
    // End of variables declaration//GEN-END:variables
}
